FROM zabbix/zabbix-web-apache-mysql:latest

ARG DB_SERVER_HOST
ENV DB_SERVER_HOST=${DB_SERVER_HOST}
ARG MYSQL_USER
ENV MYSQL_USER=${MYSQL_USER}
ARG MYSQL_PASSWORD
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ARG ZBX_SERVER_HOST
ENV ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
ARG PHP_TZ
ENV PHP_TZ=${PHP_TZ}